### ISSUE TITLE
Penultimate macOS Safari doesn't load site

### ISSUE THREAD

**Issue by mattcen** [purplesyringa/site#3]
Your WebP compression is wonderfully cursed 😂 , and after reading about it in Firefox, I finally understand why I couldn't load the page on my iPhone 8, or Safaro on macOS 13 (Ventura); they presumably don't support WebP (adequately).

Unfortunately the nojs version *also* doesn't load because, obviously, they support JavaScript.

I wonder if there's a way for you to also use JS to detect whether the JS engine has adequate support, and have it *also* redirect to nojs.html?

**Comment by purplesyringa** [comment]
I've wrapped everything in a big try..catch. I've verified that this redirects correctly on user agents without *WebGL* support, but I'm not sure if this is going to suffice for *WebP*-less clients. Can you please verify that the fix worked?

**Comment by mattcen** [comment]
Nice one! Yes, I confirm that my old version of Safari now redirects to nojs.html and shows the full page!

Thanks so much!
